c---------------------------------------------------
c Include file to contain common declarations
c
c JHM, 06-16-06
c---------------------------------------------------

c        PARAMETER(ND=25)
c        PARAMETER(ND=70)
c      PARAMETER(ND=41)
c      PARAMETER(ND=52)
c         PARAMETER(ND=51)
c           PARAMETER(ND=75)
          PARAMETER(ND=101)
c     PARAMETER(ND=201)

          implicit real*8(A-H,O-Z)  
