      SUBROUTINE AERCON
      INCLUDE 'PHOTOCHEM/INPUTFILES/parameters.inc'
      implicit real*8(A-H,O-Z)
      character*8 PLANET
      real*8 mass
      DIMENSION PH2OL(NZ)
      INCLUDE 'PHOTOCHEM/DATA/INCLUDE/PHOTABLOK.inc'
      INCLUDE 'PHOTOCHEM/DATA/INCLUDE/SATBLK.inc'
      INCLUDE 'PHOTOCHEM/DATA/INCLUDE/SULBLK.inc'
      INCLUDE 'PHOTOCHEM/DATA/INCLUDE/NBLOK.inc'
      INCLUDE 'PHOTOCHEM/DATA/INCLUDE/BBLOK.inc'


C
C   THIS SUBROUTINE FINDS THE WEIGHT PERCENT OF H2SO4 IN THE
C   PARTICLES AND THE H2SO4 VAPOR PRESSURE, GIVEN THE TEMPERATURE
C   AND H2O CONCENTRATION AT EACH ALTITUDE.
C          IT ALSO CALCULATES THE SATURATION VAPOR PRESSURE OVER
C     SOLID (ORTHORHOMBIC) S8.
C
      zero = 0.0
      one = 1.0
      
      do J=1,NZ
        PH2OL(J) = LOG(USOL(LH2O,J)*P(J))
      enddo

      DO 2 J=1,NZ
      DO 3 K=1,NF
      KT = K
      IF(VH2O(K,J) .LT. PH2OL(J)) GO TO 4
   3  CONTINUE
   4  KT1 = max(KT-1,1)
C
C   PH2OL(J) LIES BETWEEN VH2O(KT,J) AND VH2O(KT1,J)
      FR = 1.
      IF(KT .GT. KT1) FR = (PH2OL(J) - VH2O(KT1,J))/(VH2O(KT,J) -
     2  VH2O(KT1,J))
      FR = max(FR, zero)
      FR = min(FR, one)
      FSULF(J) = (FR*FTAB(KT) + (1.-FR)*FTAB(KT1)) * 0.01
      H2SO4L = FR*VH2SO4(KT,J) + (1.-FR)*VH2SO4(KT1,J)
      H2SO4S(J) = EXP(H2SO4L)/P(J)
   2  CONTINUE
C
C   FIND THE SATURATION MIXING RATIO OF S8
      DO J=1,NZ
      PLOG10 = (11.664 - 5166./T(J)) * 0.981
      PSATS8 = 10.**PLOG10 * 1.013/760.
      S8S(J) = PSATS8/P(J)
      enddo
C
      RETURN
      END
