      SUBROUTINE SATRAT(T,PSAT)
      
C
C   THIS SUBROUTINE FINDS THE SATURATION VAPOR PRESSURE (PSAT) AT
C   A GIVEN TEMPERATURE T.
C
      PARAMETER(NT=76)
      COMMON/FBLOK/TTAB(NT),PVAP(NT),DPVAP(NT),SVC(NT),DSV(NT),DSC(NT)
     2  ,RHOV(NT),DRHOV(NT),BETAM(70,75),TCP(75),PCP(70),DPDTL(70,75),
     3  DRDTL(70,75)
      COMMON/SBLOK/P0P,T0P,R,SUBL

      RV = R/18.
C
      IF(T.GT.646.96) GO TO 3
      IF(T.GT.273.16) GO TO 2
      HL = SUBL
      PSAT = P0P * EXP(-HL/RV * (1./T - 1./T0P))
      RETURN
C
   2  TC = T - 273.15
      N = TC/5. + 1
      FR = (TC - TTAB(N))/(TTAB(N+1) - TTAB(N))
      PSAT = FR*PVAP(N+1) + (1.-FR)*PVAP(N)
      RETURN
C
   3  PSAT = 1.E38
      RETURN
      END
